version: "3.9"
services:
  mysql:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  postgres:
    # $ docker compose exec postgres psql -U postgres
    # postgres=# select * from foo;
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  sqlserver:
    # $ docker compose exec sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U SA
    # 1> use test1
    # 2> go
    # 1> select * from foo;
    # 2> go
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Passw0rd
  oracle:
    # $ docker compose exec oracle sqlplus system/password@XE
    # SQL> select * from foo;
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: "password"
  db2:
    # $ docker compose exec db2 bash -c "su - db2inst1"
    # % db2 connect to testdb
    # % db2 "select * from foo"
    image: icr.io/db2_community/db2:11.5.8.0
    ports:
      - "50000:50000"
    environment:
      LICENSE: accept
      DBNAME: testdb
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
    privileged: true
